baseurl = "/"
languageCode = "pt-br"
title = "Workshop P4H"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
relativeurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-119683862-1"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
	# General information
	author = "P4H"
	description = "Material para Workshop P4H"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/p4hUSP/workshops_2018.2"

	version = ""
	logo = "logo_r4sc.jpg"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	github   = "p4hUSP"
	email    = "p4husp@gmail.com"
	slack    = "p4husp"
	facebook = "p4hUSP"
	
[[menu.main]]
	name   = "Importar"
	url    = "importar/"
	weight = 5
	
[[menu.main]]
	name   = "Manipular"
	url    = "manipular/"
	weight = 10

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
